language: java
before_script:
  - export TZ=America/Sao_Paulo

jdk:
  - oraclejdk8

notifications:
    email:
        recipients:
            - jefperito@gmail.com
            - diego+travisnfe@devmonsters.com
        on_success: change
        on_failure: always

sudo: false

after_success:
  - mvn -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID clean cobertura:cobertura coveralls:report